#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Hierarchy
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=20gb
#SBATCH --partition=long
#SBATCH --nodelist=xgph18
#SBATCH --nodes=1
python hierarchy_run.py