#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=hierarchy
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=20
#SBATCH --ntasks=1
srun python hierarchy_run.py