#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=dao
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
srun python dao_run.py