#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=3
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=300gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
srun python hierarchy_run.py