#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=swx
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=70gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
python dao_run_3.py