#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=cent5
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=300gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
python dao_run_across_incentive_0.6.py