#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=0.3
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=300gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --nodes=1
python dao_run_across_incentive_0.3.py