#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=tD
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
srun python dao_run_1.py