#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Autonomy_high
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --nodes=1
srun python autonomy_run_high_performer.py