#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=TTT_D
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
python dao_run.py