#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Threshold
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=40gb
#SBATCH --partition=long
#SBATCH --nodelist=xgph13
#SBATCH --nodes=1
python dao_run.py