#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Tn_H
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
python hierarchy_run.py