#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Tur_a
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --nodelist=xgph14
#SBATCH --nodes=1
python autonomy_run.py