#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=i_a
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
srun python autonomy_run.py