#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=TbR_H
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --nodes=1
srun python hierarchy_run_1.py