#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=asymmetry_across_incentive
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=70gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
#SBATCH --exclude=xcne[0-7]
python Asymmetry_across_incentive_strength.py