#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=strength
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
#SBATCH --exclude=xcne[0-7]
python dao_run_across_incentive_strength.py