#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Asymmetry
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --nodelist=xgph[10-14,16-19]
python dao_run.py