#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=TbF_A
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=300gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
srun python autonomy_run.py