#!/bin/bash
#SBATCH --time=02:00:00
#SBATCH --job-name=Incen
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=140gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=30
#SBATCH --nodes=1
python dao_run.py