#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=p1p2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --nodes=1
srun python run_2.py