#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=p1p2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=51
#SBATCH --nodes=1
python run.py