#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Threshold
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=80
#SBATCH --nodes=1
python dao_run.py