#!/bin/bash
#SBATCH --time=10:00:00
#SBATCH --job-name=h_time
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=20gb
#SBATCH --partition=long
python hierarchy_across_time_linear.py