#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=A_rate_lr_3
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --exclude=xcng[0-1]
srun python autonomy_run_3.py