#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Population
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=400gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=102
#SBATCH --nodes=1
srun python population_run.py