#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Asymmetry
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=20gb
#SBATCH --partition=long
#SBATCH --nodelist=xgph12
#SBATCH --nodes=1
python dao_run.py