#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=ascas
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=230gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
python dao_run.py