#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=TbR_A
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=52
#SBATCH --nodes=1
python autonomy_run.py