#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=TT_D
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=5gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
python dao_run.py